export const productsDetails = [
  {
    productId: 1,
    name: "BOPP White Tapes",
    productType: "Packing Tapes",
    material: "BOPP",
    adhesiveSide: "Single Side",
    length: "100 Meter (m)",
    color: "Transparent",
    imgLink: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/31pzRyrYD4L.jpg",
  },
  {
    productId: 2,
    name: "BOPP Customised Tapes",
    adhesiveSide: "Single Side",
    length: "100 Meter (m)",
    width: "48 Millimeter (mm)",
    imgLink: "https://5.imimg.com/data5/FR/DD/MY-1737502/logo-printed-tape-500x500.jpg",
    description:
      "Our printed tapes provides high esthetics and visual branding required for the extra mileage you can take through packing. Our BOPP carton sealing tape with water-based acrylic adhesive has excellent adhesion, superior impact resistance, excellent shelf life, and UV resistance. We use advanced coating technology, pneumatically controlled drying system, rotogravure printing, and slitting equipment to ensure excellent quality of the tapes. Our products are known for their pressure-sensitive precision, excellent finishing, adhesiveness, and appropriate thickness along with exceptional packaging. we can also customize printed and other tapes on request.",
  },
  {
    productId: 3,
    name: "BOPP Super Clear Tape",
    productType: "Packing Tape",
    material: "BOPP",
    adhesiveSide: "Single Side",
    width: "48 Millimeter (mm)",
    length: "100 Meter (m)",
    color: "Transparent",
    imgLink: "https://5.imimg.com/data5/AJ/XW/MY-14068985/bopp-super-clear-tape-500x500.jpg",
    description:
      "The commonly used adhesive packing tapes that are used in sealing medium to heavy-duty carton sealing, shipping, inventory management and in logistics industries are actually BOPP tapes.",
  },
  {
    productId: 4,
    name: "BOPP Color Tapes",
    productType: "Packing Tapes",
    material: "BOPP",
    adhesiveSide: "Single Side",
    width: "48 Millimeter (mm)",
    imgLink: "https://5.imimg.com/data5/RI/XP/MY-2045989/bopp-tapes-500x500.jpg",
    length: "100 Meter (m)",
    features: [
      "Waterproof surface",
      "Tear resistance",
      "High strength",
      "Fine finish",
    ],
    description:
      "We have carved a niche in this domain, as leading manufacturer and supplier of the finest quality BOPP Color Tapes. Owing to its effective stickiness and sturdy design, provided tapes are highly cherished among our clients. With the help of sophisticated machines, the offered tape is manufactured using supreme grade raw materials under the observation of deft professionals. In addition to this, our esteemed patrons can easily avail the provided BOPP Color Tapes at reasonable rates from us.",
  },
  {
    productId: 5,
    name: "BOPP Packing Tapes",
    productType: "Packing Tape",
    material: "BOPP",
    adhesiveSide: "Single Side",
    imgLink: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71nXZEQQiEL._SL1500_.jpg",
    width: "48 Millimeter (mm)",
    length: "100 Meter (m)",
    description:
      "Our printed tapes provides high esthetics and visual branding required for the extra mileage you can take through packing. Our BOPP carton sealing tape with water-based acrylic adhesive has excellent adhesion, superior impact resistance, excellent shelf life, and UV resistance. We use advanced coating technology, pneumatically controlled drying system, rotogravure printing, and slitting equipment to ensure excellent quality of the tapes. Our products are known for their pressure-sensitive precision, excellent finishing, adhesiveness, and appropriate thickness along with exceptional packaging. we can also customize printed and other tapes on request.",
  },
  {
    productId: 6,
    name: "BOPP Brown Tapes",
    productType: "Sealing Tapes",
    material: "BOPP",
    adhesiveSide: "Single Side",
    imgLink: "https://5.imimg.com/data5/ZI/TQ/FE/SELLER-21563518/brown-bopp-tape-1000x1000.jpeg",
    color: "White",
    use: "For Buisness Use",
    supplyAbility: "10 Box per day",
  },
  {
    productId: 7,
    name: "Carpainter Masking Tape",
    adhesiveSide: "Single Side",
    shelfLife: "2-3 years",
    adhesiveType: "Solvent adhesive",
    imgLink: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/31u3vSn4Q4L.jpg",
    color: "White",
    use: "Carton Sealing",
    supplyAbility: "10 Box per day",
    description:
      "Masking tape, also known as painter's tape, is a type of pressure-sensitive tape made of a thin and easy-to-tear paper, and an easily released pressure-sensitive adhesive. It is available in a variety of widths. It is used mainly in painting, to mask off areas that should not be painted.",
  },
  {
    productId: 8,
    name: "Painter Masking Tape",
    adhesiveSide: "Single Side",
    length: "20 Meter (m)",
    material: "Kraft Paper",
    imgLink: "https://rukminim1.flixcart.com/image/416/416/kdvzwcw0/drafting-tape/7/7/g/masking-tape-for-drawing-painting-hansh-original-imafup56ru6rehw3.jpeg?q=70",
    adhesiveType: "Rubber",
    color: "Off White",
    use: "Masking",
    width: "24 Millimeter (mm)",
    description:
      "Masking tape, also known as painter's tape, is a type of pressure-sensitive tape made of a thin and easy-to-tear paper, and an easily released pressure-sensitive adhesive. It is available in a variety of widths. It is used mainly in painting, to mask off areas that should not be painted.",
  },
];
